[features]
seeds = false
[programs.devnet]
myepicproject = "GzX76Vk8XLLJxYkpAAwaeu94DuJXTzLQ8zkog4xp34vd"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/zachboerger/.config/solana/devnet.json"

[scripts]
test = "node tests/myepicproject.js"
